version: '3.4'

services:
  postgres:
    image: mdillon/postgis:11
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: evermos
    volumes:
       - pg-data:/var/lib/postgresql/data
       - "./schema-database/:/backup"

volumes:
  pg-data:
